### PR TITLE
Next web branch

### PR DESCRIPTION
**Pull request by chirchir12**
## Building with Responsive Design
1. Aligned all elements with float and flex or grid.
2. Used browser width breakpoints to place media-queries for fluid design.
3. Applied HTML semantics and CSS standard practices.
4. Double-checked page layout, so it won't brake on smaller screens.

### CODE REVIEW

**Review by mikenath223 — CHANGES_REQUESTED** [review]
Hi Team 👋

Nice job on this. 👍

However, there seems to be mainly an issue with the number of sections you added.

- [ ] - Kindly watch [this screencast](https://www.loom.com/share/f90c6ebde42445279538571e56e629ef) and take note of the issues raised and fix accordingly. 

Please fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by edieatha** [comment]
## TSE code review recommendations applied
* Added missing block elements in both desktop and mobile views

**Comment by uryelah** [comment]
Hello **Edie Atha Kawanguzi & Chirchir ChirChir**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**First of all great making the site responsive and fixing the issues from the last review!🌟**

There are still some issues to fix, mainly to do with the style of the page and spacing of its elements, read the requirements below carefully and keep your code game strong 💪 

---------     

## Required Changes 🏗 👷‍♀ 

- [x] The top three articles and articles inside each section should use the semantic HTML `<article>` tag, not a `<div>`. Make sure to change them.

- [x] On medium screens the navbar should have the logo on the left and the main article should not have the logo over it anymore. 
Compare your version with the original one below and make sure they look the same for medium size breaking points:
Screenshot_2020-04-24 Next Web
Screenshot_2020-04-24 TNW - International technology news, business and culture(2)


----


- [x] Also make sure to add the orange gradient under the main article logo on wide screens like below:
Screenshot_2020-04-24 TNW - International technology news, business and culture(3)

---

- [x] Make sure your article's text is not spilling out or overflowing on medium to small screens.
**Notice how some of the text is almost unreadable:**
Screenshot_2020-04-24 Next Web(1)
**Compare how in the original there's come padding below ant the text keeps its spacing:**
Screenshot_2020-04-24 TNW - International technology news, business and culture(4)

---

- [ ] The 'Apps', 'Gears', etc, sections should have links for their titles as the articles above them have. 

---

- [x] Make sure that the 'Latest News' articles images have the same proportions on mobile as the ones in the original site. Compare your clone with the original version:
Screenshot_2020-04-24 Next Web(2)
Screenshot_2020-04-24 TNW - International technology news, business and culture(5)

----


- [x]  There's a small horizontal scroll issue on small screens. Make sure to fix it wither with the 'overflow' property or making sure all the page items have a width at most equal to the body.

- [x] Style the 'Latest Deals' section articles with a similar text to the original, title and price under it, and similar images, they can be repeated.
Screenshot_2020-04-24 Next Web(3)
Screenshot_2020-04-24 TNW - International technology news, business and culture(6)

-----

- [x] Add the missing icons and font style to the footer.

----

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by edieatha** [comment]
## TSE Code Review changes applied
1. Used <article> tag instead of <div> tag on billboard section.
2. Added logo to navbar in medium screens
3. Added orange gradient to billboard images
4. Fixed spilling text in billboard section
5. 'Apps', 'Gears', etc, sections have links for their titles
6. 'Latest News' articles images have the same proportions on mobile as the ones in the original site.
7. Fixed small horizontal scroll issue on small screens.
8. Styled the 'Latest Deals' section articles with a similar text to the original, title and price under it

**Comment by uryelah** [comment]
Good with the fixes guys!
------
## Your project is approved! 🎊 🥅 💛 
### 
**You may close this Pull Request and merge the changes**

----

**Keep being awesome devs and good luck with your next project!**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by chirchir12** [comment]
the branch was approved and ready to be merged

**Pull request merged**
